language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nmandiwal/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true nmandiwal/docker-react npm run test   